### ISSUE TITLE
gnome-vagrant-indicator not working on Ubuntu 19.10 Gnome 3.34.1

### ISSUE THREAD

**Issue by fikoulli** [fffilo/gnome-vagrant-indicator#15]
Dear,

First thanks for your work and wish you full success.

This is my first time with vagrant and I was really happy to find an extension that will help me to (may be) understand it quickly.

While installing vagrant indicator on Ubuntu 19.10 / Gnome 3.34.1, I had an issue.
 (note: I tried all the three installation methods)

![Screenshot from 2019-11-07 09-27-56](https://user-images.githubusercontent.com/42391916/68372676-9efb6900-0141-11ea-8a1e-07c516b0dca3.png)

![Screenshot from 2019-11-07 09-29-09](https://user-images.githubusercontent.com/42391916/68372682-a15dc300-0141-11ea-8863-e7035798f20d.png)

In system logs I found these errors :

![Screenshot from 2019-11-07 09-37-51](https://user-images.githubusercontent.com/42391916/68373064-5abc9880-0142-11ea-98a0-8a51699ed284.png)

A/

JS ERROR: Extension gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com: TypeError: this._construct is not a function
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_ui@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js:97:24
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js:43:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
enable@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/extension.js:40:17
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:482:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:457:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:491:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:522:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:32:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
start@resource:///org/gnome/shell/ui/main.js:141:5
@<main>:1:31

B/ 

JS ERROR: Extension gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com: TypeError: this._construct is not a function
newClass@resource:///org/gnome/gjs/modules/_legacy.js:114:32
_ui@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js:97:24
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
_init@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/indicator.js:43:9
wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
enable@/home/j/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/extension.js:40:17
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:132:13
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:264:21
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:482:13
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:17
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:457:9
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:491:13
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:522:13
init@resource:///org/gnome/shell/ui/extensionSystem.js:32:9
_initializeUI@resource:///org/gnome/shell/ui/main.js:245:5
start@resource:///org/gnome/shell/ui/main.js:141:5
@<main>:1:31

C/

Some code accessed the property 'CommandSystem' on the module 'vagrant'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

D/

Some code accessed the property 'CommandVagrant' on the module 'vagrant'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.

Hope it helps.

I'm available for testing.
Best regards

**Comment by fffilo** [comment]
Still using Ubuntu 16.04 (gnome shell 3.18), so i didn't test it on newer version. As soon as i find time I will install newer version and test it.

**Comment by fikoulli** [comment]
Thx a lot.
ur the best.

**Comment by fffilo** [comment]
Try new version:

    wget https://raw.githubusercontent.com/fffilo/gnome-vagrant-indicator/master/install.sh -O - | bash

...and reload gnome-shell...

**Comment by bapiraju** [comment]
I tried with the new version above, I still get the same error.

**Comment by bapiraju** [comment]
[log messages.txt](https://github.com/fffilo/gnome-vagrant-indicator/files/3939962/log.messages.txt)

**Comment by fffilo** [comment]
I guess i need to rewrite everything to es6...

**Comment by fffilo** [comment]
Try now...
